/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provadejava;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur
 */
public class TelaRegistrarPedido extends javax.swing.JFrame {

    /**
     * Creates new form TelaRegistrarPedido
     */
    public TelaRegistrarPedido() {
    initComponents();

    // Listeners confiáveis
    rbtnCliente.addItemListener(e -> {
        if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            carregarClientes();
        }
    });

    rbtnFornecedor.addItemListener(e -> {
        if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            carregarFornecedores();
        }
    });

    // Seleciona "Cliente" por padrão e carrega os dados logo ao abrir
    rbtnCliente.setSelected(true);
    carregarClientes();
}

    
    private Map<String, Cliente> mapaClientes = new HashMap<>();
    private Map<String, Fornecedor> mapaFornecedores = new HashMap<>();
    
    public void carregarClientes() {
        cmbClienteFornecedor.removeAllItems();
        mapaClientes.clear();

        ClienteDAO cDAO = new ClienteDAO();
        List<Cliente> lista = cDAO.getCliente();
        
        if (lista != null) {
            for (Cliente c : lista) {
                String chave = c.getNome(); // ou nomeFantasia, se for o que aparece na tela
                mapaClientes.put(chave, c);
                cmbClienteFornecedor.addItem(chave);
            }
        }
    }

    
    private void carregarFornecedores() {
        cmbClienteFornecedor.removeAllItems();
        mapaFornecedores.clear();
        
        FornecedorDAO fDAO = new FornecedorDAO();
        List<Fornecedor> lista = fDAO.getFornecedor();
        
        if (lista != null) {
            for (Fornecedor f : lista) {
                String chave = f.getNome(); // idem
                mapaFornecedores.put(chave, f);
                cmbClienteFornecedor.addItem(chave);
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpClienteFornecedor = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblTipoNota = new javax.swing.JLabel();
        rbtnCliente = new javax.swing.JRadioButton();
        rbtnFornecedor = new javax.swing.JRadioButton();
        btnRegistrarPedido = new javax.swing.JButton();
        lblClienteFornecedor = new javax.swing.JLabel();
        cmbClienteFornecedor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitulo.setText("Tela de registro de pedido");

        lblTipoNota.setText("Tipo do Pedido:");

        grpClienteFornecedor.add(rbtnCliente);
        rbtnCliente.setText("Cliente");

        grpClienteFornecedor.add(rbtnFornecedor);
        rbtnFornecedor.setText("Fornecedor");

        btnRegistrarPedido.setText("Registrar");
        btnRegistrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPedidoActionPerformed(evt);
            }
        });

        lblClienteFornecedor.setText("Registrar: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRegistrarPedido))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTipoNota)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnFornecedor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblClienteFornecedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbClienteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 65, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoNota)
                    .addComponent(rbtnCliente)
                    .addComponent(rbtnFornecedor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteFornecedor)
                    .addComponent(cmbClienteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnRegistrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPedidoActionPerformed
        // TODO add your handling code here:
        try {
            Pedido pedido = new Pedido();
            PedidoDAO pedidoDAO = new PedidoDAO();

            // Define data atual
            pedido.setData(new java.sql.Timestamp(System.currentTimeMillis()));

            String nomeSelecionado = (String) cmbClienteFornecedor.getSelectedItem();
            if (rbtnCliente.isSelected()) {
                pedido.setTipoNota(1);
                Cliente cliente = mapaClientes.get(nomeSelecionado);
                pedido.setIdCliente(cliente.getId());

         } else if (rbtnFornecedor.isSelected()) {
             pedido.setTipoNota(2);
             Fornecedor fornecedor = mapaFornecedores.get(nomeSelecionado);
             pedido.setIdFornecedor(fornecedor.getId());
          }

          // Chama o DAO
          pedidoDAO.registrarPedido(pedido);

          JOptionPane.showMessageDialog(this, "Pedido registrado com sucesso!");

      } catch (Exception e) {
          JOptionPane.showMessageDialog(this, "Erro ao registrar pedido: " + e.getMessage());
          e.printStackTrace();
        }
    }//GEN-LAST:event_btnRegistrarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistrarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPedido;
    private javax.swing.JComboBox<String> cmbClienteFornecedor;
    private javax.swing.ButtonGroup grpClienteFornecedor;
    private javax.swing.JLabel lblClienteFornecedor;
    private javax.swing.JLabel lblTipoNota;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtnCliente;
    private javax.swing.JRadioButton rbtnFornecedor;
    // End of variables declaration//GEN-END:variables
}
